### ISSUE TITLE
Desktop app stuck at login window

### ISSUE THREAD

**Issue by ssh37010** [facebookresearch/projectaria_tools#12] opened 2023-08-21 02:40 UTC
Hi,

I tried to use the desktop app on Mac (macOS Ventura Version 13.4) for MPS service. However it keep stuck in the login window and prevent me from preceeding. 
Is there a fix for that? 

BTW, the link for documentation on webpage https://portal.projectaria.com/home#tools (for app downloading) refers to the old version (https://facebookresearch.github.io/Aria_data_tools/) instead of the newer version (https://facebookresearch.github.io/projectaria_tools/) which is a bit misleading. 

Thanks

**Comment by princeward** [comment] 2023-08-21 04:25
The instructions on this page should should solve your issue:
https://facebookresearch.github.io/projectaria_tools/docs/ARK/troubleshooting/clear_cache

**Comment by bilalsou** [comment] 2023-08-23 10:50
We have fixed the issue in the next version of the Desktop App but for now you can try to clear the cache as indicated above. Let us know if this does not work out for you

**Comment by ssh37010** [comment] 2023-08-23 19:23
Clearing the cache solved the problem. Thanks!

**Comment by SeaOtocinclus** [comment] 2023-08-24 16:57
Closing the issue since the problem is resolved. @ssh37010 Feel free to reopen if you have more questions along the stated issues.

**Closed by SeaOtocinclus** 2023-08-24 16:57 UTC
