### ISSUE TITLE
Failed to generate MPS and Point cloud

### ISSUE THREAD

**Issue by wasilone11** [facebookresearch/projectaria_tools#47] opened 2023-12-16 10:41 UTC
We are using Meta Aria to capture data for driver intention anticipation. The clips we capture are usually 15-20 seconds long. On the desktop app, we can get the CSV file for the gaze. However, it always gives an error while generating the trajectory and semi-dense point cloud csv's/

**Comment by SeaOtocinclus** [comment] 2023-12-16 19:14
Hello @wasilone11 
1. Do you have an output that you can download?
2. Can you check if you have a `summary.json` in the trajectory folder and look for the `"status"` it can help identify which steps is failing
3. Your sequences are very short, can you try with a longer sequence?

**Comment by vijay609** [comment] 2023-12-16 19:51
@wasilone11 
Please follow the steps suggeted by @SeaOtocinclus .
If that doesn't help, are you able to share the `transaction_id` of the failed run, which you can obtain from the desktop app ?

**Comment by wasilone11** [comment] 2023-12-18 05:38
1. No, it fails to generate an output for anything other than the gaze.
2. It works perfectly fine with short sequences captured indoors. 
3. For example, this is the ID for a video for which trajectory and point cloud information failed to process: ID: 08dae386-44cb-4df3-8378-04bd7444e088

**Comment by wasilone11** [comment] 2023-12-18 05:42
Also, I get the internal server error. Message: Error uploading file

**Comment by vijay609** [comment] 2023-12-18 18:04
> 1. No, it fails to generate an output for anything other than the gaze.
> 2. It works perfectly fine with short sequences captured indoors.
> 3. For example, this is the ID for a video for which trajectory and point cloud information failed to process: ID: 08dae386-44cb-4df3-8378-04bd7444e088

@wasilone11 
I am not able to find transaction id `08dae386-44cb-4df3-8378-04bd7444e088` in the backend. Can you please recheck this on your side? The transaction id refers to the id on this screen
![image](https://github.com/facebookresearch/projectaria_tools/assets/11788943/05692c1a-332b-49b3-a12d-a525c0770c13)

**Comment by wasilone11** [comment] 2023-12-18 18:12
![aria_error](https://github.com/facebookresearch/projectaria_tools/assets/40135735/7520ab71-5235-4052-9c27-7b76b52fc5c1)

All of these fail to process the trajectory and semi-dense point cloud.

**Comment by vijay609** [comment] 2023-12-18 18:21
Sorry for the inconvenience. I will see what I can find. These requests are over a month old and we don't save any debugging information older that a few weeks.
Are you able to submit any one of the failed recordings one more time, please?
That will help me get the latest processing logs.

**Comment by vijay609** [comment] 2023-12-18 19:03
> ![aria_error](https://private-user-images.githubusercontent.com/40135735/291371718-7520ab71-5235-4052-9c27-7b76b52fc5c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjM0NDAsIm5iZiI6MTcwMjkyMzE0MCwicGF0aCI6Ii80MDEzNTczNS8yOTEzNzE3MTgtNzUyMGFiNzEtNTIzNS00MDUyLTljMjctN2I3NmI1MmZjNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4MTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNzZhNzY0NmViYTU1MzYwNWE5MjFmMDQ4ZDUxYmI0Mzg3MjJlNzkzNjc3YzIxODcwYzBhYWJlOGViM2RmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lNc5f4KwR3zRdLvSS2wy664AwFTyZCApDgkZIq-RyaQ)
> 
> All of these fail to process the trajectory and semi-dense point cloud.

@wasilone11 I looked into these requests and it looks like only eye gaze was requested and no trajectory or semi-dense points. As I mentioned in my earlier reply, please submit any one of these recordings and request trajectory + point clouds. We will then be able to debug this better.

**Comment by wasilone11** [comment] 2023-12-18 20:46
The problem is that I am not able to process the trajectory and sdpc at all. 
![error](https://github.com/facebookresearch/projectaria_tools/assets/40135735/52e1c6d3-734d-49f2-9c53-e7d514e31436)

This is what happens if i try to.

**Comment by wasilone11** [comment] 2023-12-18 20:49
If I request for gaze-point, trajectory and semi-dense point cloud, the uploading and processing happens properly but then the message shown in the snippet above is shown. However, it happens only when I request these for the data captured in a moving vehicle. When I capture data walking around the lab, it gets processed properly,

**Comment by wasilone11** [comment] 2023-12-18 20:51
> > ![aria_error](https://private-user-images.githubusercontent.com/40135735/291371718-7520ab71-5235-4052-9c27-7b76b52fc5c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjM0NDAsIm5iZiI6MTcwMjkyMzE0MCwicGF0aCI6Ii80MDEzNTczNS8yOTEzNzE3MTgtNzUyMGFiNzEtNTIzNS00MDUyLTljMjctN2I3NmI1MmZjNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4MTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNzZhNzY0NmViYTU1MzYwNWE5MjFmMDQ4ZDUxYmI0Mzg3MjJlNzkzNjc3YzIxODcwYzBhYWJlOGViM2RmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lNc5f4KwR3zRdLvSS2wy664AwFTyZCApDgkZIq-RyaQ)
> > All of these fail to process the trajectory and semi-dense point cloud.
> 
> @wasilone11 I looked into these requests and it looks like only eye gaze was requested and no trajectory or semi-dense points. As I mentioned in my earlier reply, please submit any one of these recordings and request trajectory + point clouds. We will then be able to debug this better.

I always request all of the three together but as shown is the snippet above, it fails to generate the trajectory and semi-dense point cloud. Does it have anything do with the IMU and non-inertial frame of reference in case of a moving car?

**Comment by wasilone11** [comment] 2023-12-18 21:11
![traj_f](https://github.com/facebookresearch/projectaria_tools/assets/40135735/4e5c99c7-cf02-4bf5-ba56-b64c0b0b50eb)

**Comment by vijay609** [comment] 2023-12-18 23:35
> ![traj_f](https://private-user-images.githubusercontent.com/40135735/291409594-4e5c99c7-cf02-4bf5-ba56-b64c0b0b50eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzU4MTgsIm5iZiI6MTcwMjkzNTUxOCwicGF0aCI6Ii80MDEzNTczNS8yOTE0MDk1OTQtNGU1Yzk5YzctY2YwMi00YmY1LWJhNTYtYjY0YzBiMGI1MGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIxMzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MzE5MWQ0YTU3ZGI5YTBjZDlhMzRkZTliNmY3NzA1NDI3MDNhNzczNzdkYWE4Yjc1NzJkMGUwZWI5ZThiYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO1rWfTHuq2HYQVmkY103SY40zQ8zaa-1U1CWETPWMw)

Yes. Moving frame of reference is not yet supported. This error is likely from that. Could you please share the transaction id for this request ?

**Comment by vijay609** [comment] 2023-12-18 23:39
> > ![traj_f](https://private-user-images.githubusercontent.com/40135735/291409594-4e5c99c7-cf02-4bf5-ba56-b64c0b0b50eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzU4MTgsIm5iZiI6MTcwMjkzNTUxOCwicGF0aCI6Ii80MDEzNTczNS8yOTE0MDk1OTQtNGU1Yzk5YzctY2YwMi00YmY1LWJhNTYtYjY0YzBiMGI1MGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIxMzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MzE5MWQ0YTU3ZGI5YTBjZDlhMzRkZTliNmY3NzA1NDI3MDNhNzczNzdkYWE4Yjc1NzJkMGUwZWI5ZThiYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO1rWfTHuq2HYQVmkY103SY40zQ8zaa-1U1CWETPWMw)
> 
> Yes. Moving frame of reference is not yet supported. This error is likely from that. Could you please share the transaction id for this request ?

Nevermind. I found it. We will investigate the logs and get back. Very likely this is due to a moving car. Will get back to you with confirmation.

**Comment by vijay609** [comment] 2023-12-19 00:17
> > > ![traj_f](https://private-user-images.githubusercontent.com/40135735/291409594-4e5c99c7-cf02-4bf5-ba56-b64c0b0b50eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzU4MTgsIm5iZiI6MTcwMjkzNTUxOCwicGF0aCI6Ii80MDEzNTczNS8yOTE0MDk1OTQtNGU1Yzk5YzctY2YwMi00YmY1LWJhNTYtYjY0YzBiMGI1MGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIxMzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MzE5MWQ0YTU3ZGI5YTBjZDlhMzRkZTliNmY3NzA1NDI3MDNhNzczNzdkYWE4Yjc1NzJkMGUwZWI5ZThiYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO1rWfTHuq2HYQVmkY103SY40zQ8zaa-1U1CWETPWMw)
> > 
> > 
> > Yes. Moving frame of reference is not yet supported. This error is likely from that. Could you please share the transaction id for this request ?
> 
> Nevermind. I found it. We will investigate the logs and get back. Very likely this is due to a moving car. Will get back to you with confirmation.

Investigated the logs and without looking at the vrs file, which we don't have access to since it gets deleted immediately after processing, it definitely points that the issue is coming from visual frame and inertial frame not in agreement.
This is something that is not supported today.

**Comment by wasilone11** [comment] 2023-12-21 06:30
We had Kiran from your group at our lab a few days back. He said that although not publicly available, your team has solutions to process trajectory and semi-dense point cloud for such scenarios. Can you please get in touch with him for a follow-up?

**Comment by feixue94** [comment] 2024-01-09 16:22
![image](https://github.com/facebookresearch/projectaria_tools/assets/49382877/d093f800-b0a8-4bfc-a7bb-059f5573011b)

same uploading error.

**Comment by SeaOtocinclus** [comment] 2024-01-10 17:16
Closing this issue since it moved to our academic partner support https://facebookresearch.github.io/projectaria_tools/docs/support

**Closed by SeaOtocinclus** 2024-01-10 17:16 UTC
